# Generated by Django 3.1.2 on 2021-06-16 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('street', models.CharField(max_length=75, null=True)),
                ('city', models.CharField(max_length=75, null=True)),
                ('postalcode', models.CharField(max_length=7, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('bio', models.CharField(max_length=150, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
