# Generated by Django 3.2.3 on 2021-06-02 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 2, 2, 19, 38230)),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 2, 2, 19, 38197)),
        ),
    ]
