# Generated by Django 3.2.3 on 2021-06-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210629_0520'),
        ('session', '0002_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='organization.organization'),
        ),
    ]
