# Generated by Django 3.2.3 on 2021-06-02 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20210602_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 2, 5, 44, 375389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 2, 5, 44, 375360, tzinfo=utc)),
        ),
    ]
