# Generated by Django 3.2.3 on 2021-06-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_session_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='day',
        ),
    ]
