# Generated by Django 3.2.3 on 2021-06-29 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_alter_session_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
