# Generated by Django 3.2.3 on 2021-06-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20210602_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='private_coment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='debrief',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
