# Generated by Django 3.2.3 on 2021-06-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(),
        ),
    ]
