# Generated by Django 3.2.3 on 2021-06-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_rename_date_session_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
