# Generated by Django 3.1.2 on 2021-06-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_auto_20210610_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
