# Generated by Django 3.2.4 on 2021-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
